//= require_self
//= require vendor/jquery-1.7.2
//= require vendor/json2
//= require vendor/underscore
//= require vendor/backbone
//= require config
//= require_tree ./models
//= require_tree ./templates
//= require_tree ./views
//= require_tree ./collections
//= require router
//= require boot
